# Generated by Django 6.0.3 on 2026-03-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comomodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('bolsa', models.CharField(max_length=20)),
                ('unidade', models.CharField(max_length=30)),
                ('moeda', models.CharField(max_length=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'commodities',
            },
        ),
    ]
