-- AgroComex — Modelo Fisico do Banco de Dados
-- Dialeto: PostgreSQL
-- Gerado a partir dos models Django (3a Forma Normal)
-- Atualizado em: 2026-03-23

-- ------------------------------------------------------------
-- auth_user (tabela nativa do Django)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS auth_user (
    id           SERIAL          PRIMARY KEY,
    username     VARCHAR(150)    NOT NULL UNIQUE,
    email        VARCHAR(254)    NOT NULL DEFAULT '',
    password     VARCHAR(128)    NOT NULL,
    first_name   VARCHAR(150)    NOT NULL DEFAULT '',
    last_name    VARCHAR(150)    NOT NULL DEFAULT '',
    is_active    BOOLEAN         NOT NULL DEFAULT TRUE,
    is_staff     BOOLEAN         NOT NULL DEFAULT FALSE,
    is_superuser BOOLEAN         NOT NULL DEFAULT FALSE,
    date_joined  TIMESTAMP       NOT NULL,
    last_login   TIMESTAMP
);

-- ------------------------------------------------------------
-- usuarios
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER         UNIQUE REFERENCES auth_user(id) ON DELETE PROTECT,
    criado_em     TIMESTAMP       NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMP       NOT NULL
);

-- ------------------------------------------------------------
-- commodities
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS commodities (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo  VARCHAR(10)  NOT NULL,
    nome    VARCHAR(100) NOT NULL,
    bolsa   VARCHAR(20)  NOT NULL,
    unidade VARCHAR(30)  NOT NULL,
    moeda   VARCHAR(5)   NOT NULL,
    ativo   BOOLEAN      NOT NULL DEFAULT TRUE
);

-- ------------------------------------------------------------
-- tipos_derivativo
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tipos_derivativo (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(50)  NOT NULL,
    rotulo          VARCHAR(50)  NOT NULL,
    descricao       TEXT,
    requer_barreira BOOLEAN      NOT NULL DEFAULT FALSE,
    requer_posicao  BOOLEAN      NOT NULL DEFAULT FALSE
);

-- ------------------------------------------------------------
-- meses_contrato_futuro
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS meses_contrato_futuro (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commodity_id    BIGINT      NOT NULL REFERENCES commodities(id) ON DELETE PROTECT,
    codigo_mes      VARCHAR(1)  NOT NULL,
    ano             SMALLINT    NOT NULL,
    data_vencimento DATE        NOT NULL,
    ticket_completo VARCHAR(20),
    ativo           BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_mes_contrato UNIQUE (commodity_id, codigo_mes, ano)
);

-- ------------------------------------------------------------
-- cache_dados_mercado
-- Obs.: serie historica local para calculo de volatilidade.
--       Possivel exclusao no futuro.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cache_dados_mercado (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commodity_id     BIGINT      NOT NULL REFERENCES commodities(id) ON DELETE PROTECT,
    data_preco       DATE        NOT NULL,
    preco_fechamento INTEGER     NOT NULL,
    fonte            VARCHAR(50),
    obtido_em        TIMESTAMP   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_cache_dados UNIQUE (commodity_id, data_preco, fonte)
);

-- ------------------------------------------------------------
-- solicitacoes_analise
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS solicitacoes_analise (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         BIGINT       NOT NULL REFERENCES usuarios(id) ON DELETE PROTECT,
    commodity_id       BIGINT       NOT NULL REFERENCES commodities(id) ON DELETE PROTECT,
    tipo_derivativo_id BIGINT       NOT NULL REFERENCES tipos_derivativo(id) ON DELETE PROTECT,
    mes_contrato_id    BIGINT       REFERENCES meses_contrato_futuro(id) ON DELETE PROTECT,
    preco_mercado_atual INTEGER     NOT NULL,
    posicao            VARCHAR(12),
    nivel_barreira     INTEGER,
    -- valores possiveis: 'aguardanto' | 'processando' | 'concluido' | 'erro'
    status             VARCHAR(20)  NOT NULL DEFAULT 'aguardanto',
    id_tarefa_worker   VARCHAR(100),
    criado_em          TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- ------------------------------------------------------------
-- resultados_analise
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resultados_analise (
    id                     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitacao_id         BIGINT        NOT NULL REFERENCES solicitacoes_analise(id) ON DELETE CASCADE,
    nivel_acumulacao       INTEGER,
    volatilidade_utilizada NUMERIC(8,6),
    taxa_juros_utilizada   NUMERIC(8,6),
    dados_brutos           JSONB,
    calculado_em           TIMESTAMP     NOT NULL DEFAULT NOW()
);
