# Generated by Django 6.0.3 on 2026-03-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDerivativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('rotulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('requer_barreira', models.BooleanField(default=False)),
                ('requer_posicao', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tipos_derivativo',
            },
        ),
    ]
