# Generated by Django 6.0.3 on 2026-03-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_derivativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoderivativo',
            name='posicao_implicita',
            field=models.CharField(blank=True, choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor')], help_text='Se preenchido, a posicao e automaticamente definida para este tipo de contrato.', max_length=12, null=True),
        ),
    ]
