# Generated by Django 6.0.3 on 2026-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_derivativo', '0003_seed_tipos_derivativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoderivativo',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Se False, o tipo nao e ofertado na selecao de nova analise.'),
        ),
    ]
