# Generated by Django 6.0.3 on 2026-03-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
        ('usuario', '0002_add_first_last_name_to_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='commodities',
            field=models.ManyToManyField(blank=True, db_table='usuario_commodity', related_name='usuarios_m2m', to='commodities.comomodity'),
        ),
    ]
