# Generated by Django 6.0.3 on 2026-03-23 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
        ('meses_contrato_futuro', '0001_initial'),
        ('tipos_derivativo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_mercado_atual', models.IntegerField()),
                ('posicao', models.CharField(blank=True, max_length=12, null=True)),
                ('nivel_barreira', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aguardanto', 'Aguardanto'), ('processando', 'Processando'), ('concluido', 'Concluido'), ('erro', 'Erro')], default='aguardanto', max_length=20)),
                ('id_tarefa_worker', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodities.comomodity')),
                ('mes_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meses_contrato_futuro.mescontratofurturo')),
                ('tipo_derivativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos_derivativo.tipoderivativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.usuario')),
            ],
            options={
                'db_table': 'solicitacoes_analise',
            },
        ),
        migrations.CreateModel(
            name='ResultadoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acumulacao', models.IntegerField(blank=True, null=True)),
                ('volatilidade_utilizada', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('taxa_juros_utilizada', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('dados_brutos', models.JSONField(blank=True, null=True)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analises.solicitacaoanalise')),
            ],
            options={
                'db_table': 'resultados_analise',
            },
        ),
    ]
