# Generated by Django 6.0.3 on 2026-03-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoanalise',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('processando', 'Processando'), ('concluido', 'Concluido'), ('erro', 'Erro')], default='aguardando', max_length=20),
        ),
    ]
