# Generated by Django 6.0.3 on 2026-03-31 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0005_bs_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenarioAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('conservador', 'Conservador'), ('moderado', 'Moderado'), ('agressivo', 'Agressivo')], max_length=20)),
                ('fator', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_exercicio_centavos', models.IntegerField()),
                ('premio_centavos', models.IntegerField()),
                ('valor_total_centavos', models.IntegerField()),
                ('ponto_equilibrio_centavos', models.IntegerField()),
                ('nivel_risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10)),
                ('e_recomendado', models.BooleanField(default=False)),
                ('escolhido_pelo_usuario', models.BooleanField(default=False)),
                ('escolhido_em', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenarios', to='analises.resultadoanalise')),
            ],
            options={
                'db_table': 'cenarios_analise',
                'unique_together': {('resultado', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='PontoCurvaResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_centavos', models.IntegerField()),
                ('resultado_centavos', models.IntegerField()),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_curva', to='analises.cenarioanalise')),
            ],
            options={
                'db_table': 'pontos_curva_resultado',
                'ordering': ['preco_centavos'],
            },
        ),
    ]
