# Generated by Django 6.0.3 on 2026-06-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0009_add_cenario_proposto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoanalise',
            name='barreira_tipo',
            field=models.CharField(blank=True, choices=[('knock_in', 'Knock-in (entrada)'), ('knock_out', 'Knock-out (saida)')], max_length=10, null=True),
        ),
    ]
