# Generated by Django 6.0.3 on 2026-03-23 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesContratoFurturo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mes', models.CharField(max_length=1)),
                ('ano', models.SmallIntegerField()),
                ('data_vencimento', models.DateField()),
                ('ticket_completo', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodities.comomodity')),
            ],
            options={
                'db_table': 'meses_contrato_futuro',
                'unique_together': {('commodity', 'codigo_mes', 'ano')},
            },
        ),
    ]
