# Generated by Django 6.0.3 on 2026-03-23 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheDadosMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_preco', models.DateField()),
                ('preco_fechamento', models.IntegerField()),
                ('fonte', models.CharField(blank=True, max_length=50, null=True)),
                ('obtido_em', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodities.comomodity')),
            ],
            options={
                'db_table': 'cache_dados_mercado',
                'unique_together': {('commodity', 'data_preco', 'fonte')},
            },
        ),
    ]
