# Generated by Django 6.0.3 on 2026-03-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_periodic_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMacroeconomicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(choices=[('USD_BRL', 'Dolar Comercial Venda (BRL)'), ('EUR_BRL', 'Euro Venda (BRL)'), ('SELIC', 'Taxa SELIC (% a.a.)'), ('IPCA', 'IPCA (% mensal)')], max_length=20)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fonte', models.CharField(max_length=50)),
                ('obtido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dados_macroeconomicos',
                'indexes': [models.Index(fields=['indicador', 'data'], name='dados_macro_indicad_91db46_idx')],
                'unique_together': {('indicador', 'data')},
            },
        ),
    ]
