# Generated by Django 6.0.3 on 2026-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0004_update_task_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedadosmercado',
            name='preco_fechamento',
            field=models.BigIntegerField(),
        ),
    ]
