# Generated by Django 6.0.3 on 2026-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0006_add_analise'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='quantidade_toneladas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='resultado',
            field=models.TextField(blank=True, default=''),
        ),
    ]
