# Generated by Django 6.0.3 on 2026-03-25 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0007_analise_add_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analise',
        ),
    ]
