# Generated by Django 6.0.3 on 2026-03-27 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
        ('dados', '0008_remove_analise_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportacaoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('valor_fob_usd', models.BigIntegerField()),
                ('fonte', models.CharField(max_length=50)),
                ('obtido_em', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodities.comomodity')),
            ],
            options={
                'db_table': 'exportacao_mensal',
                'unique_together': {('commodity', 'data_referencia', 'fonte')},
            },
        ),
    ]
