# Generated by Django 6.0.3 on 2026-03-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0009_create_exportacao_mensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacaomensal',
            name='fonte',
            field=models.CharField(choices=[('COMEXSTAT_EXPORT', 'ComexStat — Exportacao')], max_length=50),
        ),
    ]
