# Generated by Django 6.0.3 on 2026-04-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0011_migrate_comexstat_to_exportacao_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedadosmercado',
            name='justificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cachedadosmercado',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedadosmercado',
            name='motivo_qualidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedadosmercado',
            name='qualidade',
            field=models.CharField(choices=[('OK', 'OK'), ('SUSPEITO', 'SUSPEITO'), ('INVALIDO', 'INVALIDO')], default='OK', max_length=10),
        ),
        migrations.AddField(
            model_name='dadosmacroeconomicos',
            name='justificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dadosmacroeconomicos',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosmacroeconomicos',
            name='motivo_qualidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosmacroeconomicos',
            name='qualidade',
            field=models.CharField(choices=[('OK', 'OK'), ('SUSPEITO', 'SUSPEITO'), ('INVALIDO', 'INVALIDO')], default='OK', max_length=10),
        ),
        migrations.AddField(
            model_name='exportacaomensal',
            name='justificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exportacaomensal',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportacaomensal',
            name='motivo_qualidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportacaomensal',
            name='qualidade',
            field=models.CharField(choices=[('OK', 'OK'), ('SUSPEITO', 'SUSPEITO'), ('INVALIDO', 'INVALIDO')], default='OK', max_length=10),
        ),
    ]
