# Generated by Django 6.0.3 on 2026-06-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0009_add_cenario_proposto'),
        ('chatbot', '0002_analise_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='analise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='analises.solicitacaoanalise'),
        ),
    ]
