# Generated by Django 6.0.3 on 2026-06-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0010_add_barreira_tipo'),
        ('chatbot', '0003_conversation_analise'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_proativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='is_proativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='lida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_proativas', to='analises.solicitacaoanalise'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='tipo_alerta',
            field=models.CharField(blank=True, choices=[('cenario_nao_escolhido', 'Cenario nao escolhido'), ('cotacao_cruzou', 'Cotacao cruzou nivel'), ('melhor_momento', 'Melhor momento')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='EstadoAlertaAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('cenario_nao_escolhido', 'Cenario nao escolhido'), ('cotacao_cruzou', 'Cotacao cruzou nivel'), ('melhor_momento', 'Melhor momento')], max_length=30)),
                ('ultimo_estado', models.CharField(max_length=30)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_alerta', to='analises.solicitacaoanalise')),
            ],
            options={
                'db_table': 'chatbot_estado_alerta_analise',
                'unique_together': {('solicitacao', 'tipo_alerta')},
            },
        ),
    ]
