# Generated by Django 6.0.3 on 2026-06-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversation_is_proativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='tipo_alerta',
            field=models.CharField(blank=True, choices=[('cenario_nao_escolhido', 'Cenario nao escolhido'), ('cotacao_cruzou', 'Cotacao cruzou nivel'), ('melhor_momento', 'Melhor momento'), ('abertura', 'Abertura proativa')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estadoalertaanalise',
            name='tipo_alerta',
            field=models.CharField(choices=[('cenario_nao_escolhido', 'Cenario nao escolhido'), ('cotacao_cruzou', 'Cotacao cruzou nivel'), ('melhor_momento', 'Melhor momento'), ('abertura', 'Abertura proativa')], max_length=30),
        ),
    ]
